### PR TITLE
Start to implement a new version of client.py.

### PR DESCRIPTION
**Pull request by raduiman**
* Rewrite all the functions to pull dates from object. (only for GIT part)
 * Add client-test.py and repositories.json.
 * Change the filename for HG json files.

I started to implement the method to pull dates direct from GIT object. Without using requests library.

!!! Unfortunately, I did not manage to finish a functional version yet. I've encountered a few errors.. I will work on them on my next shift. 

Please have a look to the new test files. You can see how we should manage the GitHub information.

### CODE REVIEW

**Comment by raduiman** [comment]
TODO:
 * we should add exception blocks when we get the commit dates:
   - git returns us an empty object for some of commits (in general the very old commit) and it broke the script
   
I hope that this start-script will give you the idea about how it works.

**Comment by raduiman** [comment]
Documentation: https://pygithub.readthedocs.io/en/latest/github_objects/Organization.html?highlight=organization

Here you can see how we can get information using parameters:
 * get commits dates since a specific date
 * get the last X commits
 * get commits made by $author
 * etc

**Comment by raduiman** [comment]
TODO: We'll need to adapt the MD file creation method.

**Comment by Akhliskun** [comment]
This PR was been fixed by https://github.com/Akhliskun/firefox-infra-changelog/pull/77

**Pull request closed without merging**
